# Escribe los logs en un archivo
logging.file.name=logs/tienda.log

# Nivel de log por paquete
logging.level.com.paradigmas=INFO

# Formato en consola (opcional, para que sea mas legible)
logging.pattern.console=%d{HH:mm:ss} [%level] %logger{20} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{20} - %msg%n